export type Country = { name: string; code: string; flag: string };

export const COUNTRIES: Country[] = [
  { name: 'Albania',        code: 'AL', flag: '🇦🇱' },
  { name: 'Andorra',        code: 'AD', flag: '🇦🇩' },
  { name: 'Angola',         code: 'AO', flag: '🇦🇴' },
  { name: 'Argentina',      code: 'AR', flag: '🇦🇷' },
  { name: 'Armenia',        code: 'AM', flag: '🇦🇲' },
  { name: 'Australia',      code: 'AU', flag: '🇦🇺' },
  { name: 'Austria',        code: 'AT', flag: '🇦🇹' },
  { name: 'Azerbaijan',     code: 'AZ', flag: '🇦🇿' },
  { name: 'Belgium',        code: 'BE', flag: '🇧🇪' },
  { name: 'Brazil',         code: 'BR', flag: '🇧🇷' },
  { name: 'Bulgaria',       code: 'BG', flag: '🇧🇬' },
  { name: 'Canada',         code: 'CA', flag: '🇨🇦' },
  { name: 'Croatia',        code: 'HR', flag: '🇭🇷' },
  { name: 'Cyprus',         code: 'CY', flag: '🇨🇾' },
  { name: 'Czech Republic', code: 'CZ', flag: '🇨🇿' },
  { name: 'Denmark',        code: 'DK', flag: '🇩🇰' },
  { name: 'Estonia',        code: 'EE', flag: '🇪🇪' },
  { name: 'Finland',        code: 'FI', flag: '🇫🇮' },
  { name: 'France',         code: 'FR', flag: '🇫🇷' },
  { name: 'Germany',        code: 'DE', flag: '🇩🇪' },
  { name: 'Greece',         code: 'GR', flag: '🇬🇷' },
  { name: 'Hungary',        code: 'HU', flag: '🇭🇺' },
  { name: 'Iceland',        code: 'IS', flag: '🇮🇸' },
  { name: 'Ireland',        code: 'IE', flag: '🇮🇪' },
  { name: 'Italy',          code: 'IT', flag: '🇮🇹' },
  { name: 'Latvia',         code: 'LV', flag: '🇱🇻' },
  { name: 'Liechtenstein',  code: 'LI', flag: '🇱🇮' },
  { name: 'Lithuania',      code: 'LT', flag: '🇱🇹' },
  { name: 'Luxembourg',     code: 'LU', flag: '🇱🇺' },
  { name: 'Malta',          code: 'MT', flag: '🇲🇹' },
  { name: 'Netherlands',    code: 'NL', flag: '🇳🇱' },
  { name: 'New Zealand',    code: 'NZ', flag: '🇳🇿' },
  { name: 'Norway',         code: 'NO', flag: '🇳🇴' },
  { name: 'Poland',         code: 'PL', flag: '🇵🇱' },
  { name: 'Portugal',       code: 'PT', flag: '🇵🇹' },
  { name: 'Romania',        code: 'RO', flag: '🇷🇴' },
  { name: 'Singapore',      code: 'SG', flag: '🇸🇬' },
  { name: 'Slovakia',       code: 'SK', flag: '🇸🇰' },
  { name: 'Slovenia',       code: 'SI', flag: '🇸🇮' },
  { name: 'Spain',          code: 'ES', flag: '🇪🇸' },
  { name: 'Sweden',         code: 'SE', flag: '🇸🇪' },
  { name: 'Switzerland',    code: 'CH', flag: '🇨🇭' },
  { name: 'United Kingdom', code: 'GB', flag: '🇬🇧' },
  { name: 'United States',  code: 'US', flag: '🇺🇸' },
];
